reconFaces/gestao_pessoas/urls.py
from django.contrib import admin
from django.urls import path, include
from pessoas import urls as pessoas_urls
from home import urls as home_urls

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', include(home_urls)),
    path('pessoas/', include(pessoas_urls)),
    path('login/', LoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reconFaces/home/urls.py
from django.urls import path
from .views import  home, meu_logout

urlpatterns = [
    path('', home, name='home'),
    path('logout/', meu_logout, name="logout"),
]

reconFaces/pessoas/urls.py
from django.urls import path
from .views import listar
from .views import nova
from .views import alterar
from .views import deletar
from .views import reconhecimento
from .views import listarContagem

urlpatterns = [
    path('listar/', listar, name="pessoa_listar"),
    path('nova/', nova, name="pessoa_nova"),
    path('alterar/<int:id>/', alterar, name="pessoa_alterar"),
    path('deletar/<int:id>/', deletar, name="pessoa_deletar"),
    path('reconhecimento/', reconhecimento, name='pessoa_reconhecimento'),
    path('contagem/',listarContagem , name="pessoa_contagem"),
]

reconFaces/home/models.py
from django.db import models

# Create your models here.

reconFaces/pessoas/models.py
from django.db import models
import os

## função que retorna o nome da pessoa para que a imagem fique com o nome da pessoa
def salvar_imagem(instance, filename):

    dir = os.listdir('media/fotos/')

    instance.numero = 1

    ## verifica se tem imagens salvas para essa pessoa se estiver verifica qual foto foi apaga e passa o numero dela
    ## paga que a imagem seja salva
    if(dir) :

        for pessoa in dir:
            if instance.nome == pessoa:
                fotosAntigas = os.listdir('media/fotos/' + instance.nome + "/")

                for num,foto in enumerate(fotosAntigas):
                    instance.numero = ultimoNumeroFoto(instance.nome) + 1

                    f = foto.split('.')
                    n = int(f[1])

                    if num > n:
                        instance.numero = num

    nomeArquivo = filename.split(".")

    return 'fotos/'+instance.nome+ '/'+instance.nome+ '.' + str(instance.numero)+ '.' + nomeArquivo[1]

def ultimoNumeroFoto(nome):
    fotosAntigas = os.listdir('media/fotos/' + nome + "/")
    f = fotosAntigas[fotosAntigas.__len__() - 1].split('.')
    n = int(f[1])

    return n


class Pessoa(models.Model):
    nome = models.CharField(max_length=30)
    email = models.CharField(max_length=120)
    cpf = models.CharField(max_length=11)
    celular = models.CharField(max_length=11)
    idade = models.IntegerField()
    numero = 0
    foto1 = models.ImageField(upload_to=salvar_imagem)
    foto2 = models.ImageField(upload_to=salvar_imagem)
    foto3 = models.ImageField(upload_to=salvar_imagem)
    foto4 = models.ImageField(upload_to=salvar_imagem)
    foto5 = models.ImageField(upload_to=salvar_imagem)
    foto6 = models.ImageField(upload_to=salvar_imagem)

    def __str__(self):
        return self.nome


class Contagem(models.Model):
    identificadas = models.IntegerField()

    def __str__(self):
        return self.identificadas

reconFaces/pessoas/forms.py
from django.forms import ModelForm
from .models import Pessoa, Contagem

class PersonForm(ModelForm):
    class Meta:
        model = Pessoa
        fields = ['nome', 'cpf', 'idade', 'email', 'celular', 'foto1', 'foto2', 'foto3', 'foto4', 'foto5', 'foto6']

reconFaces/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout

def home(request):
    return render(request, 'home.html')

def meu_logout(request):
   logout(request)
   return redirect('home')

reconFaces/pessoas/views.py
import os

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from reconhecimento.reconhecimento import Reconhecimento
from .models import Pessoa, Contagem
from .forms import PersonForm

from reconhecimento.treinamento import Treinamento
from pessoas.arquivos import apagar_arquivos, apagar_foto, apagar_treinamento

import threading

@login_required
def listar(request):
    pessoas = Pessoa.objects.all()
    return render(request, 'lista.html', {'pessoas': pessoas})

def nova(request):
    form = PersonForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()

        ## se houver um treinamento  apaga o treinamento
        dir = os.listdir('media/treinamento/')
        if dir.__len__() > 0:
         apagar_treinamento()

        ## abre uma nova thread para fazer o treinamento das pessoas
        treinamento = Treinamento()
        th = threading.Thread(target=treinamento.gerarTreinamento)
        th.start()

        return redirect('pessoa_listar')

    return render(request, 'pessoa_form.html', {'form': form})

## função que auxilia a verificação das fotos
def verificar(request, nome):

     for foto in request.FILES:
         n = int(foto.split('foto')[1])
         verificaFotoAtualComAntiga(nome, foto, (n-1))

     ## apos verificar as fotos exclui o treinamento caso tenha uma foto novo
     if request.FILES:
         ## se houver um treinamento  apaga o treinamento
         dir = os.listdir('media/treinamento/')
         if dir.__len__() > 0:
           apagar_treinamento()

## função que recebe a foto atual e verifica se a mesma é diferente das antigas se for apaga a antiga
def verificaFotoAtualComAntiga(nome, fotoAtual, numeroFoto):

    fotosAntigas = os.listdir('media/fotos/'+nome+"/")

    for pos,foto in enumerate(fotosAntigas):
        f = foto.split('.')
        n = int(f[1])

        if numeroFoto == n:
            numeroFoto = pos
            break

    fotoAntiga = fotosAntigas[numeroFoto]

    if fotoAntiga != fotoAtual:
        apagar_foto(nome, fotoAntiga)

@login_required
def alterar(request, id):
    pessoa = get_object_or_404(Pessoa, pk=id)
    form = PersonForm(request.POST or None, request.FILES or None, instance=pessoa)

    nome_antigo = pessoa.nome

    if form.is_valid():
        ## verifica as imagens antes de alterar
        verificar(request, pessoa.nome)

        form.save()

        ## apaga o arquivo de treinamento e refaz o treinamento
        if nome_antigo != request.POST.get('nome'):

            dir = os.listdir('media/treinamento/')
            if dir.__len__() > 0:
              apagar_treinamento()

            ## abre uma nova thread para fazer o treinamento das pessoas
            treinamento = Treinamento()
            th = threading.Thread(target=treinamento.gerarTreinamento)
            th.start()

        ## gera um novo treinamento caso mude uma foto
        if request.FILES:
            ## abre uma nova thread para fazer o treinamento das pessoas
            treinamento = Treinamento()
            th = threading.Thread(target=treinamento.gerarTreinamento)
            th.start()

        return redirect('pessoa_listar')

    return render(request, 'pessoa_form.html', {'form': form, 'pessoa': pessoa})

@login_required
def deletar(request, id):
    pessoa = get_object_or_404(Pessoa, pk=id)

    if request.method == 'POST':
        pessoa.delete()

        ## após remover a pessoa exclui suas fotos e seus arquivos de treinamento
        apagar_arquivos(pessoa.nome)

        ## só realiza o treinamento se houver uma foto dessa pessoa
        dirs = os.listdir('media/fotos/')
        if dirs.__len__() > 0:
          ## abre uma nova thread para fazer o treinamento das pessoas
          treinamento = Treinamento()
          th = threading.Thread(target=treinamento.gerarTreinamento)
          th.start()

        return redirect('pessoa_listar')

    return render(request, 'pessoa_delete_confirm.html', {'pessoa': pessoa})

def reconhecimento(request):
  recon = Reconhecimento()
  recon.indentificar()

  return redirect('pessoa_listar')

def listarContagem(request):
    contagem = Contagem.objects.all()
    return render(request, 'contagem.html', {'contagem': contagem[0]})

reconFaces/home/templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
</head>
<body>

   <h1>Seja bem vindo</h1>

    {% if user.is_authenticated %}
        <p>Ola {{user.username}}</p>
        <a href="{% url 'logout' %}">Sair</a>
    {% else %}
         <a href="{% url 'login' %}">Entrar</a>
    {% endif %}
</body>
</html>

reconFaces/pessoas/templates/contagem.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/contagem.css' %}">
  <title>Totalidade de Pessoas</title>
</head>
<body>

  <body>

    <h1 class="contador_pessoas">
        Número Total de Pessoas
    </h1>

    <div id="countdown_dashboard">

      <div class="dashp">
        {% if contagem.identificadas < 10 %}
          <div class ="numero">
		    {{contagem.identificadas}}
	       </div>
        {% endif %}

        {% if contagem.identificadas > 9 %}
          <div class ="numero1">
		    {{contagem.identificadas}}
	       </div>
        {% endif %}
      </div>

    </div>
  </body>

</body>
</html>

reconFaces/pessoas/templates/lista.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/listar.css' %}">
  <title>Lista de Pessoas Cadastradas</title>
</head>
<body>

 <h1>Lista de Pessoas Cadastradas</h1>
  <div class="container">
    <div class="col">
        {% if user.is_authenticated %}
            <p>Ola {{user.username }}
                <a href="{% url 'logout' %}">
                    <span class="badge badge-danger">Sair</span>
                </a>
            </p>
        {% endif %}
    </div>

    <div class="table table-bordered">
      <table>
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Cpf</th>
          <th>Celular</th>
          <th>Idade</th>
          <th>Opções</th>
        </tr>

        {% for pessoa in pessoas %}
          <tr>
            <td>{{pessoa.nome}}</td>
            <td>{{pessoa.email}}</td>
            <td>{{pessoa.cpf}}</td>
            <td>{{pessoa.celular}}</td>
            <td>{{pessoa.idade}}</td>
            <td><input onClick="window.open('{% url 'pessoa_alterar' pessoa.id %}')" type="image" id="iconEditar" src="{% static 'img/editar.png' %}" alt="Editar">
               <input onClick="window.open('{% url 'pessoa_deletar' pessoa.id %}')" type="image" id="iconExcluir" src="{% static 'img/lixeira.png' %}" alt="Excluir"></td>
          </tr>
        {% endfor %}
      </table>
    </div>

    <br>  <br>  <br>

    <a href="{% url 'pessoa_nova' %}" class="btn btn-primary"> Nova Pessoa</a>

    <a href="{% url 'pessoa_reconhecimento' %}" class="btn btn-success espaco_botao_reconhecer"> Reconhecer</a>

  </div>
</body>
</html>

reconFaces/pessoas/templates/pessoa_delete_confirm.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>Excluir Pessoa</title>
</head>
<body>

    <h1>Tem certeza que deseja deletar {{ pessoa.nome }} </h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Deletar</button>
    </form>

</body>
</html>

reconFaces/pessoas/templates/pessoa_form.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/cadastropessoa.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'javascript/cadastro.js' %}"></script>
    <title>Informações Pessoa</title>
</head>
<body>

    <div class="container center">
        <div class="col-sm-7 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h1 class="card-title text-center"> Registro Pessoa </h1>

                    <form  method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="col-sm-9, center">
                            <label> Nome:</label>
                            <input type="text" class="form-control" name="nome" value="{{pessoa.nome}}" maxlength="30" required="" id="id_nome">
                        </div>

                        <div class="col-sm-9, center">
                            <label> Email:</label>
                            <input type="email" class="form-control" name="email" value="{{pessoa.email}}" maxlength="120" required id="id_email">
                        </div>

                        <div class="col-sm-6, center">
                            <label> CPF:</label>
                            <input type="text" class="form-control" name="cpf" value="{{pessoa.cpf}}" maxlength="11" required id="id_cpf">
                        </div>

                        <div class="col-sm-6, center">
                            <label> Celular:</label>
                            <input type="text" class="form-control" name="celular" value="{{pessoa.celular}}" maxlength="11" required id="id_celular">
                        </div>

                        <div class="col-sm-6, center">
                            <label> Idade:</label>
                            <input type="number" class="form-control" name="idade" value="{{pessoa.idade}}" required id="id_idade">
                        </div>

                        <div class="col-sm-6, center">
                            <label class="tam_fonte"> Fotos:</label>
                        </div>

                        <div class="row espaco_img">
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-header">Foto 1</div>
                                        <div class="card-body">
                                            <img id="foto1" src="{{pessoa.foto1.url}}" class="img-fluid rounded"/>
							                <div>
                                                <input type="file" name="foto1"  accept="image/*" id="id_foto1" hidden="hidden" onchange="carregaFoto1(event)" />
                                                <button type="button" id="btn1" class="btn btn-primary espaco_img" > <label for="id_foto1"> <span>Ulpoad</span></label> </button>
                                            </div>
                                        </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-header">Foto 2</div>
                                        <div class="card-body">
                                            <img id="foto2"  src="{{pessoa.foto2.url}}" class="img-fluid rounded"/>
                                            <div>
                                               <input type="file" name="foto2" accept="image/*" id="id_foto2" hidden="hidden" onchange="carregaFoto2(event)" />
                                               <button type="button" id="btn2" class="btn btn-primary espaco_img" > <label for="id_foto2"> <span>Ulpoad</span></label> </button>
                                            </div>
                                        </div>
                                </div>
                            </div>
                        </div>

                        <div class="row espaco_img">
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-header">Foto 3</div>
                                        <div class="card-body">
                                            <img id="foto3" src="{{pessoa.foto3.url}}" class="img-fluid rounded"/>
                                            <div>
                                               <input type="file" name="foto3" accept="image/*" id="id_foto3" hidden="hidden" onchange="carregaFoto3(event)" />
                                               <button type="button" id="btn3" class="btn btn-primary espaco_img" > <label for="id_foto3"> <span>Ulpoad</span></label> </button>
                                            </div>
                                        </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-header">Foto 4</div>
                                        <div class="card-body">
                                            <img id="foto4" src="{{pessoa.foto4.url}}" class="img-fluid rounded"/>
                                                <div>
                                                    <input type="file" name="foto4" accept="image/*" id="id_foto4" hidden="hidden" onchange="carregaFoto4(event)" />
                                                    <button type="button" id="btn4" class="btn btn-primary espaco_img" > <label for="id_foto4"> <span>Ulpoad</span></label> </button>
                                                </div>
                                        </div>
                                </div>
                            </div>

                        </div>

                        <div class="row espaco_img">
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-header">Foto 5</div>
                                        <div class="card-body">
                                            <img id="foto5" src="{{pessoa.foto5.url}}" class="img-fluid rounded"/>
                                            <div>
                                                <input type="file" name="foto5" accept="image/*" id="id_foto5" hidden="hidden" onchange="carregaFoto5(event)" />
                                                <button type="button" id="btn5" class="btn btn-primary espaco_img" > <label for="id_foto5"> <span>Ulpoad</span></label> </button>
                                            </div>
                                        </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-header">Foto 6</div>
                                        <div class="card-body">
                                            <img id="foto6" src="{{pessoa.foto6.url}}" class="img-fluid rounded"/>
                                            <div>
                                                <input type="file" name="foto6" accept="image/*" id="id_foto6" hidden="hidden" onchange="carregaFoto6(event)" />
                                                <button type="button" id="btn6" class="btn btn-primary espaco_img"> <label for="id_foto6"> <span>Ulpoad</span></label> </button>
                                            </div>
                                        </div>
                                </div>
                            </div>
                        </div>


                        <div class="center">
                            <button type="submit" class="btn btn-lg btn-primary btn-block text-uppercase">Concluir</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</body>
</html>